!!python/object/new:openpoints.utils.config.EasyConfig
dictitems:
  CUDA_VISIBLE_DEVICES: 0
  batch_size: 32
  ckpt_dir: log/scanobjectnn/scanobjectnn-train-pointnet++-ngpus1-seed8979-20250205-112929-FfD933BLCgUUgicY3Gexv4/checkpoint
  criterion_args: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      NAME: SmoothCrossEntropy
      label_smoothing: 0.3
  dataloader: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      num_workers: 6
  dataset: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      common: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          NAME: ScanObjectNNHardest
          data_dir: ./data/ScanObjectNN/h5_files/main_split
      train: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          split: train
      val: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          num_points: 1024
          split: val
  datatransforms: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      kwargs: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          angle:
          - 0.0
          - 1.0
          - 0.0
          gravity_dim: 1
          scale:
          - 0.9
          - 1.1
      train:
      - PointsToTensor
      - PointCloudCenterAndNormalize
      val:
      - PointsToTensor
      - PointCloudCenterAndNormalize
      vote:
      - PointCloudRotation
  deterministic: false
  dist_backend: nccl
  dist_url: tcp://localhost:8888
  distributed: false
  epoch: 0
  epochs: 250
  exp_dir: log/scanobjectnn/scanobjectnn-train-pointnet++-ngpus1-seed8979-20250205-112929-FfD933BLCgUUgicY3Gexv4
  exp_name: pointnet++
  feature_keys: pos
  finetune: false
  grad_norm_clip: 10
  ignore_index: null
  launcher: mp
  layer_decay: 0
  load_path: null
  local_rank: 0
  log_dir: log/scanobjectnn/scanobjectnn-train-pointnet++-ngpus1-seed8979-20250205-112929-FfD933BLCgUUgicY3Gexv4
  log_path: log/scanobjectnn/scanobjectnn-train-pointnet++-ngpus1-seed8979-20250205-112929-FfD933BLCgUUgicY3Gexv4/scanobjectnn-train-pointnet++-ngpus1-seed8979-20250205-112929-FfD933BLCgUUgicY3Gexv4.log
  logname: null
  lr: 0.002
  min_lr: 0.0001
  mode: train
  model: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      NAME: BaseCls
      cls_args: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          NAME: ClsHead
          mlps:
          - 512
          - 256
          norm_args: !!python/object/new:openpoints.utils.config.EasyConfig
            dictitems:
              norm: bn1d
          num_classes: 15
      encoder_args: !!python/object/new:openpoints.utils.config.EasyConfig
        dictitems:
          NAME: PointNet2Encoder
          act_args: !!python/object/new:openpoints.utils.config.EasyConfig
            dictitems:
              act: relu
          aggr_args: !!python/object/new:openpoints.utils.config.EasyConfig
            dictitems:
              NAME: convpool
              anisotropic: false
              feature_type: dp_fj
              reduction: max
          conv_args: !!python/object/new:openpoints.utils.config.EasyConfig
            dictitems:
              order: conv-norm-act
          group_args: !!python/object/new:openpoints.utils.config.EasyConfig
            dictitems:
              NAME: ballquery
              normalize_dp: false
              use_xyz: true
          in_channels: 4
          layers: 3
          mlps:
          - - - 64
              - 64
              - 128
          - - - 128
              - 128
              - 256
          - - - 256
              - 512
              - 1024
          norm_args: !!python/object/new:openpoints.utils.config.EasyConfig
            dictitems:
              norm: bn
          num_samples:
          - 32
          - 64
          - null
          radius:
          - 0.2
          - 0.4
          - null
          sampler: fps
          strides:
          - 2
          - 4
          - 1
          use_res: false
          width: null
  mp: false
  multiprocessing_distributed: false
  ngpus_per_node: 1
  num_classes: 15
  num_points: 1024
  optimizer: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      NAME: adamw
      weight_decay: 0.05
  opts: CUDA_VISIBLE_DEVICES=0-python
  pretrained_path: null
  print_freq: 10
  python: examples/classification/main.py
  rank: 0
  resume: false
  root_dir: log/scanobjectnn
  run_dir: log/scanobjectnn/scanobjectnn-train-pointnet++-ngpus1-seed8979-20250205-112929-FfD933BLCgUUgicY3Gexv4
  run_name: scanobjectnn-train-pointnet++-ngpus1-seed8979-20250205-112929-FfD933BLCgUUgicY3Gexv4
  save_freq: -1
  sched: cosine
  sched_on_epoch: true
  seed: 8979
  start_epoch: 1
  step_per_update: 1
  sync_bn: false
  t_max: 200
  task_name: scanobjectnn
  test: false
  use_amp: false
  use_gpu: true
  use_mask: false
  use_voting: false
  val_batch_size: 64
  val_fn: validate
  val_freq: 1
  wandb: !!python/object/new:openpoints.utils.config.EasyConfig
    dictitems:
      project: PointNeXt-ScanObjectNN
      tags:
      - scanobjectnn
      - train
      - pointnet++
      - ngpus1
      - seed8979
      use_wandb: false
  warmup_epochs: 0
  world_size: 1
